apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - postgres.yaml
  - frontend.yaml
  - secret.yaml
images:
  - name: expenses-analyzer-backend
    newTag: local
  - name: expenses-analyzer-frontend
    newTag: local
patches:
  - path: backend-kind.yaml
