apiVersion: v1
kind: Secret
metadata:
  name: expenses-db
type: Opaque
stringData:
  DATABASE_USER: expenses
  DATABASE_PASSWORD: expenses
  DATABASE_NAME: expenses
  DATABASE_HOST: postgres
  DATABASE_PORT: '5432'
