/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Expenses Analyzer API
 * Bootstrap health/scaffold API. Nest @nestjs/swagger is the runtime source.
 * OpenAPI spec version: 0.0.0
 */
import { customFetch } from './custom-fetch';
export type HealthResponseStatus = typeof HealthResponseStatus[keyof typeof HealthResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthResponseStatus = {
  ok: 'ok',
  error: 'error',
} as const;

export interface HealthResponse {
  status: HealthResponseStatus;
}

export type getHealthResponse200 = {
  data: HealthResponse
  status: 200
}

export type getHealthResponse503 = {
  data: HealthResponse
  status: 503
}
    
export type getHealthResponseSuccess = (getHealthResponse200) & {
  headers: Headers;
};
export type getHealthResponseError = (getHealthResponse503) & {
  headers: Headers;
};

export type getHealthResponse = (getHealthResponseSuccess | getHealthResponseError)

export const getGetHealthUrl = () => {


  

  return `/health`
}

export const getHealth = async ( options?: RequestInit): Promise<getHealthResponse> => {
  
  return customFetch<getHealthResponse>(getGetHealthUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
